version: "3.8"

services:
  mysqldb:
    image: "mysql:latest"
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
    volumes:
      - db:/var/lib/mysql

  stationski:
    image: nihelroui/stationski:1.0.0
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8088:8088"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2
volumes:
  db: