version: "3.8"

services:
  db-mysql:
    image: "mysql:latest"
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
    volumes:
      - db:/var/lib/mysql

  station-ski:
    depends_on:
      - db-mysql
    image: nihelroui/stationski:1.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysql-test:3306/stationSki?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.datasource.password" : "root",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "create"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
